# Generated by Django 2.2.7 on 2019-11-26 10:29

import Upload.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Upload', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='file_name',
        ),
        migrations.AlterField(
            model_name='file',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=Upload.models.upload_location),
        ),
    ]
